solution
mate-academy/py-mutable-immutable pull request #1005
Opened 2023-10-14 20:23 UTC by Andrey1104

2023-10-15 10:01 UTC, viktoria-rybenchuk requested changes

2023-10-15 10:01 UTC, viktoria-rybenchuk commented on app/main.py
> +                                collection_of_coins]}
Consider putting each key with its corresponding value on a new line for better readability.

2023-10-16 13:59 UTC, Polyakiv-Andrey requested changes

2023-10-16 13:59 UTC, Polyakiv-Andrey commented on .flake8
> +max-line-length = 96
In this file there are flake8 rules that Python developers should follow, if you made a mistake you need to fix your code not this file, return max-line-length=79

2023-10-16 13:59 UTC, Polyakiv-Andrey commented on app/main.py
> +sorted_variables = {"immutable": [lucky_number, pi, one_is_a_prime_number, name, profile_info],
Correct your code according to the following structure
<img width="205" alt="Screenshot 2023-10-16 at 16 58 49" src="https://github.com/mate-academy/py-mutable-immutable/assets/117740672/1c1a865e-6756-48b5-8813-3e9f11bd221b">

2023-10-16 14:32 UTC, Polyakiv-Andrey approved these changes
Good job!

2024-03-23 22:21 UTC, closed without merging