Develop
mate-academy/py-mutable-immutable pull request #1047
Opened 2023-11-09 21:08 UTC by Olevsky-Ivan

2023-11-10 11:39 UTC, viktoria-rybenchuk requested changes
You should make changes just in main.py. Please rollback changes in another files

2023-11-10 11:39 UTC, viktoria-rybenchuk commented on app/main.py
> +                                  name, profile_info]}
move each key on a new line

2023-11-10 16:40 UTC, closed without merging

2023-11-10 16:41 UTC, Olevsky-Ivan commented
corrected code, maybe

2023-11-11 13:34 UTC, Olevsky-Ivan commented
ALL?

2023-11-11 13:34 UTC, Olevsky-Ivan commented
all?

2023-11-11 13:35 UTC, Olevsky-Ivan commented
all?

2023-11-11 13:35 UTC, Olevsky-Ivan commented
all

2023-11-11 13:36 UTC, Olevsky-Ivan commented
open

2023-11-11 13:46 UTC, Olevsky-Ivan commented
1

2023-11-11 13:46 UTC, Olevsky-Ivan commented
1

2023-11-11 13:58 UTC, Olevsky-Ivan reviewed
all?

2023-11-11 14:00 UTC, Olevsky-Ivan commented
d

2023-11-11 14:00 UTC, Olevsky-Ivan commented
all

2023-11-11 14:04 UTC, Olevsky-Ivan commented
1

2023-11-11 16:06 UTC, Olevsky-Ivan commented
ф

2023-11-11 16:06 UTC, Olevsky-Ivan commented
Якщо я нажму, то просто залишиться комент

2023-11-11 16:07 UTC, Olevsky-Ivan commented
а

2023-11-11 16:18 UTC, Olevsky-Ivan commented
fd