Solution
mate-academy/py-mutable-immutable pull request #831
Opened 2023-08-01 19:04 UTC by rzaliznyi

2023-08-02 07:48 UTC, Dimosphen1 requested changes
Several changes were requested.

2023-08-02 07:48 UTC, Dimosphen1 commented on app/main.py
> +        sorted_variables["immutable"].append(el)
In this task, you just need to fill the `sorted_variables` dictionary with the required values, no additional logic is required.

2023-08-03 11:03 UTC, closed without merging

2023-08-03 11:08 UTC, rzaliznyi commented
Did my new solution was automatically uploaded or i need to make new pull-request?

2023-08-07 07:39 UTC, Dimosphen1 approved these changes
LGTM, nice work!