mutable_immutable
mate-academy/py-mutable-immutable pull request #833
Opened 2023-08-01 22:22 UTC by Ihor-MA

2023-08-02 10:29 UTC, Kroll410 requested changes

2023-08-02 10:29 UTC, Kroll410 commented on app/main.py
> +list_of_variables = [lucky_number, pi, one_is_a_prime_number, name,
No calculation needed, only pass variables in the correct lists

2023-08-03 07:25 UTC, Y-Havryliv requested changes
The solution is good, but you pushed redundant files. Please delete them.

2023-08-03 15:49 UTC, Kroll410 commented
Python cache files are still there

2023-08-03 15:50 UTC, Kroll410 requested changes
Remove redundant files

2023-08-03 18:41 UTC, Ihor-MA commented
> Remove redundant files



> Remove redundant files

2023-08-03 18:41 UTC, closed without merging